apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-artifacts
spec:
  storageClassName: azurefile-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-tracking
spec:
  storageClassName: azurefile-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-mlruns
spec:
  storageClassName: azurefile-rwx
