apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-scam
resources:
  - ../../base
  - rollout-canary.yaml
patches:
  - path: rollout-patch.yaml
  - path: configmap-patch.yaml
images:
  - name: ghcr.io/example/spot-scam/api
    newName: ghcr.io/your-org/spot-scam-api
    newTag: staging
