apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-scam
resources:
  - ../../../ops/k8s/base
  - rollout-canary.yaml
patches:
  - path: rollout-patch.yaml
  - path: pvc-patch.yaml
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml
images:
  - name: ghcr.io/example/spot-scam/api
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/spot-scam-api
    newTag: staging-canary
