apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-artifacts
spec:
  storageClassName: filestore-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-tracking
spec:
  storageClassName: filestore-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-mlruns
spec:
  storageClassName: filestore-rwx
