apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spot-scam-api
  labels:
    app.kubernetes.io/name: spot-scam-api
    app.kubernetes.io/part-of: spot-scam
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: spot-scam-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
