apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-artifacts
  labels:
    app.kubernetes.io/name: spot-scam-api
    app.kubernetes.io/part-of: spot-scam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-tracking
  labels:
    app.kubernetes.io/name: spot-scam-api
    app.kubernetes.io/part-of: spot-scam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spot-scam-mlruns
  labels:
    app.kubernetes.io/name: spot-scam-api
    app.kubernetes.io/part-of: spot-scam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
